### ISSUE TITLE
Using LiteLLM

### ISSUE THREAD

**Issue by ghost** [sunlight0102/azure-openai#1]
Hi @sunlight0102  , 

I saw you were using litellm - that's awesome! 

I'm the maintainer of LiteLLM. How can we make it better for you?

**Comment by sunlight0102** [comment]
Hello @krrishdholakia 

Thanks for your attention.
Now I am learning azure-openai. If I have any question and need help, will not hesitate.

Thank you again. :)

**Comment by ghost** [comment]
Hi @sunlight0102, 

I reviewed the code and saw you tried both `ChatLiteLLM` and `litellm.completion`. 

However it was commented out - https://github.com/sunlight0102/azure-openai/blob/d548696d939197cb170506560a278e6cea2073c2/api/Python/ChatGpt/__init__.py#L248

Curious - why comment it out? Did it not work?
